### ISSUE TITLE
Handling re-run NPOC/TN data

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#26]
I am working on adapting this code for TEMPEST and dont understand this function's purpose @peterregier: https://github.com/COMPASS-DOE/EXCHANGE/blob/42fd16551b3a0f23bc11370eab56f79c0dcff7e8/Processing_Scripts/water_npoc_tdn.R#L103

**Comment by peterregier** [comment]
@amyerspigg because some samples were rerun, there are two records for a number of kits, one with a npoc value and one with a tdn value. This function merges those rows via mean_if_numeric, where a normal merge would result in NAs (stats on NAs yield NAs). Lemme know if that's not clear. To see which kits this effects and how it effects them, compare npoc_blank_corrected and npoc_duplicates_removed dataframes
